In [153]:
import  numpy as np
import math
import helper

In [1]:
    data_file = open('whatsapp_messages.txt', 'r')
    data_string = data_file.read()
    full_data = data_string.split('\n')#split according to the lines
    intLength = len(full_data)
    labels = []
    for x in range(0,intLength , 1): # this can be changed depending on the data
        line = full_data[x].split(' ') #split each line according to spaces
        full_data[x] = line[1:] #store each split line array back into the original array creating a 2d array
        labels.append(line[0])

print(labels,full_data)

FileNotFoundError: [Errno 2] No such file or directory: 'whatsapp_messages.txt'

In [155]:
def countOccurrences(labels):
    distinct_labels = np.unique(labels)
    dictLabelOccur = {}#dictionary
    
    for x in distinct_labels:#initialize dictionary
        dictLabelOccur[x] = 0
        
    for x in labels:#count occurances
        dictLabelOccur[x] += 1

    return dictLabelOccur
    
    
print(countOccurrences(labels))

{'-1': 9, '1': 9}


In [156]:
def getProbabilities(labels):
    intLength = len(labels)
    dictProbLabels = countOccurrences(labels)
    for x in dictProbLabels:
        dictProbLabels[x] /= intLength
    return dictProbLabels

print(getProbabilities(labels))

{'-1': 0.5, '1': 0.5}


###### 

In [183]:
def getClassConditional(full_data,labels):
    
    #sum the data
    #-----------------------------------------------------------------------------------------------------
    distinct_labels = list(np.unique(labels))    #domain of labels
    intDistinctLabels = len(distinct_labels)     #cardinality of domain of labels
    dictClassConditionalModel = {}               #initialize dictionary
    intNumLines = len(full_data)                 #number of lines/messages in the data provided
    for x in range(0,intNumLines,1):#use range for loop instead of itemized because indecies will be usefull inside
        line = full_data[x]
        for word in line:
            if(word in dictClassConditionalModel):
                dictClassConditionalModel[word][distinct_labels.index(labels[x])] += 1 #only add to the index of the label that this word has been found at
            else:#every time a new words is found
                dictClassConditionalModel[word] = [0]*intDistinctLabels #each word will have an array of the sum of occurences of each word given each label  #{word|label}
                dictClassConditionalModel[word][distinct_labels.index(labels[x])] += 1 #only add to the index of the label that this word has been found at

    #-------------------------------------------------------------------------------------------------
    
    #calculate probabilities with laplace smoothing
    #please consult https://www.youtube.com/watch?v=gCI-ZC7irbY and https://www.youtube.com/watch?v=jSaU_iDB1Ds 
    #if laplace smoothing is being a problem
    #---------------------------------------------------------------------------------------------------
    dictLabelOccur = countOccurrences(labels)
    k = 0.01
    intNumWords = len(dictClassConditionalModel)#total number of distinct words
    for word in dictClassConditionalModel:
        for label in dictLabelOccur: 
                Prob = dictClassConditionalModel[word][distinct_labels.index(label)] 
                Prob += k
                Prob /= dictLabelOccur[label] + (k*intNumWords )#k*total number of distinct words that a variable can take(cardinality of domain of words)
                dictClassConditionalModel[word][distinct_labels.index(label)] = Prob
    key = distinct_labels#this key array will be used to get the index of each probability in the other variable
    #---------------------------------------------------------------------------------------------------
    return (dictClassConditionalModel,key)
    

        
wrkData = # takes in an array of words in a sentence
wrkLabels =  # takes in an array showing the result of each element
#dictResults = naiveBayes(full_data,labels)
dictResults,key = getClassConditional(wrkData,wrkLabels)
print(dictResults)

{'buy': [0.4879227053140097, 0.24815724815724816], 'this': [0.4879227053140097, 0.24815724815724816], 'online': [0.4879227053140097, 0.24815724815724816], 'today': [0.4879227053140097, 0.7395577395577394], 'send': [0.4879227053140097, 0.7395577395577394], 'us': [0.4879227053140097, 0.24815724815724816], 'money': [0.4879227053140097, 0.7395577395577394]}


In [173]:
def naiveBayesPredict(strLine,dictClassConditionalModel, dictProbLabels,keys):
    
    arrLine = strLine.split(' ')#split input string into words
    
    #initialize the encoding dictionary
    #------------------------------------------------------------------------------------------
    #print(dictClassConditionalModel['#key#'])
    #keys = dictClassConditionalModel.pop("#key#")
 

    dictEncode = {}
    for x in dictClassConditionalModel:
        dictEncode[x] = 0
    #-----------------------------------------------------------------------------------------   
    
   #count occurances of word to set encoding
   #-----------------------------------------------------------------------------
    for strY in arrLine:
        dictEncode[strY.lower()] +=1
  #  print(dictEncode)
    #----------------------------------------------------------------------------------------
       
            
    
    #caluculate P(strLine,dictClassConditionalModel)
    #------------------------------------------------------------------------------------------
    dictProbabilitiesXY = {}
    for x in keys:
        dictProbabilitiesXY[x] = 1
        for word in dictEncode:
            if (dictEncode[word] == 0):
                dictProbabilitiesXY[x] *= (1 - dictClassConditionalModel[word][keys.index(x)])
            else:
                dictProbabilitiesXY[x] *=  dictClassConditionalModel[word][keys.index(x)]
       
                
    #--------------------------------------------------------------------------------------------
    
    #calculate final probability
    #--------------------------------------------------------------------------
    dictProbabilitiesYX = {}
    for x in keys:

        denominator = 0
        for y in keys:
            denominator += dictProbabilitiesXY[y] * dictProbLabels[y]
            
        dictProbabilitiesYX[x] = dictProbabilitiesXY[x] * (dictProbLabels[x] / denominator)
    
    maxKey = ""
    maxValue = 0
    for key, value in dictProbabilitiesYX.items():
        if (value > maxValue):
            maxValue = value
            maxKey = key
    return maxKey

    
wrkData =  # works as in the previous functions
wrkLabels = #works as previous functions
dictResults,key = getClassConditional(wrkData,wrkLabels)
dictProbLabels = getProbabilities(wrkLabels)
strLine = # now you can encoperate the testing string

strPrediction = naiveBayesPredict(strLine,dictResults,dictProbLabels,key)
print(strPrediction)

spam


In [174]:
 
full_data.pop(3)
intEnd = len(full_data)
trainEnd = intEnd-5
training_data = full_data[0:trainEnd]
training_labels = labels[0:trainEnd]
dictClassConditionalModel,arrKeyClassConditionalModel = getClassConditional(training_data,training_labels)
dictProbLabels = getProbabilities(training_labels)

test_data = full_data[trainEnd:intEnd]
test_labels = labels[trainEnd:intEnd]


#for x in dictClassConditionalModel:
 #   print(x)

dictTestResults = {}
for arrLine in test_data:
    strLine = " ".join(arrLine)
    print(strLine)
    dictTestResults[strLine] = naiveBayesPredict(strLine,dictClassConditionalModel,dictProbLabels,arrKeyClassConditionalModel)

print(dictTestResults)

the service and the food was terrible
we had a terrible experience


KeyError: 'we'

In [2]:
wrkData = #put your own
wrkLabels = #put your own
dictResults,key = getClassConditional(wrkData,wrkLabels)
dictProbLabels = getProbabilities(wrkLabels)
strLine = #put your own

strPrediction = naiveBayesPredict(strLine,dictResults,dictProbLabels,key)
print(strPrediction)

SyntaxError: invalid syntax (<ipython-input-2-3e90ee9cc23f>, line 1)

In [161]:
#8x8 representation for question 2
import csv
import math
import random

#Handle data
def loadCsv(filename):
    lines = csv.reader(open(filename, "r"))
    dataset = list(lines)
    
    intLengthDataLine = len(dataset[0])-1
    labels = np.zeros(len(dataset))
    newdata = np.zeros((len(dataset),8,8))
    
    for i in range(len(dataset)):
        newdata[i] = np.reshape( np.array(dataset[i][0:intLengthDataLine],dtype=object), (8,8))
        labels[i] = dataset[i][intLengthDataLine]

    return (newdata,labels)

data,labels = loadCsv(#load whatever file you need )



In [186]:

import csv
import math
import random

#Handle data
def loadCsv(filename):
    lines = csv.reader(open(filename, "r"))
    dataset = list(lines)
    
    intLengthDataLine = len(dataset[0])-1
    labels = np.zeros(len(dataset))
    newdata = np.zeros((len(dataset),64))
    for i in range(len(dataset)):
        newdata[i] = np.array(dataset[i][0:intLengthDataLine],dtype=object)
        labels[i] = dataset[i][intLengthDataLine]

    return (newdata,labels)


def main():
    data,labels = loadCsv(#whatever file )
    #--------------convert to string index format
    intDataSize = len(data)
    intLineSize = len(data[0])
    arrIndexes = [[""]] *intDataSize
    for i in range(intDataSize):
        arrLine = []
        for j in range(len(data[0])):
            if (data[i][j] == 1.0):
                arrLine.append(str(j))
        arrIndexes[i] = arrLine
    
    dictResults,key = getClassConditional(arrIndexes[0:1437],labels[0:1437])
    dictProbLabels = getProbabilities(labels[0:1437])
    
    test_data = arrIndexes[1438:1797]
    test_labels = labels[1438:1797]
    
    
    confusionMatrix = np.zeros((11,11))
    for i in range(0,len(key),1):
        confusionMatrix[0,i] =key[i]
        confusionMatrix[i,0] = key[i]
    zipTestData = zip(test_data,test_labels)
    intSumTrue = 0;
    intSumTotal = 0;
    for x,y in zipTestData:
        strLine = " ".join(x)
        prediction = naiveBayesPredict(strLine,dictResults,dictProbLabels,key)
        
        if (prediction == y):
            intSumTrue += 1
        else:
            line = np.zeros(64)
            for i in x:
                line[int(i)] = 1
                
        intSumTotal += 1
        confusionMatrix[int(prediction)+1,int(y)+1] += 1
    
    print("accuracy " +str(intSumTrue/intSumTotal))
    print(confusionMatrix)
    
            
main()
        

accuracy 0.8272980501392758
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.  0.]
 [ 1. 33.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0. 21.  0.  3.  0.  0.  3.  0.  3.  1.]
 [ 3.  0.  0. 33.  1.  0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  1. 25.  0.  0.  0.  0.  0.  3.]
 [ 5.  1.  0.  0.  0. 33.  1.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  2.  0. 33.  0.  0.  1.  2.]
 [ 7.  0.  0.  0.  0.  0.  0. 34.  0.  0.  0.]
 [ 8.  0.  1.  0.  3.  2.  0.  0. 35.  2.  3.]
 [ 9.  1.  7.  0.  2.  2.  0.  0.  1. 22.  0.]
 [ 0.  0.  7.  0.  1.  0.  3.  0.  0.  5. 28.]]


In [131]:
arr = [1,2,5,4]

print(arr[0:4])

[1, 2, 5, 4]
